---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations 
summary: Cloud Volumes ONTAP está disponible en varias configuraciones de AWS y Azure. 
---
= Configuraciones admitidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP está disponible en AWS y Azure con dos opciones de precios: De pago por uso y con su propia licencia (BYOL). En el modelo de pago por uso, puede elegir entre tres configuraciones: Explorar, Standard o Premium.



== Cloud Volumes ONTAP para AWS

En AWS, puede poner en marcha Cloud Volumes ONTAP como un único sistema o como un par de alta disponibilidad.

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de instancia de EC2 | m4.xlarge  a| 
* m4.2xgrande
* r4.xlarge

 a| 
* c4.4xgrande
* c4.8x grande
* m4.4xgrande
* r4.2xgrande

 a| 
* c4.4xgrande
* c4.8x grande
* m4.xlarge
* m4.2xgrande
* m4.4xgrande
* r4.xlarge
* r4.2xgrande




| Almacenamiento subyacente 4+| SSD de uso general, SSD IOPS aprovisionados, HDD optimizados de rendimiento y HDD fríos, hasta 16 TIB por disco 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TIB | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. Si se habilita la clasificación por niveles de datos, el límite de capacidad de un sistema permanece igual. El límite de capacidad incluye tanto discos como almacenamiento de objetos.
. La organización en niveles de los datos es compatible con Cloud Volumes ONTAP Standard, Premium y BYOL.
. Al seleccionar un tipo de instancia de EC2, puede especificar si es una instancia compartida o una instancia dedicada.
. El rendimiento de escritura mejorado es compatible con el uso de unidades SSD de EBS con Cloud Volumes ONTAP Standard, Premium y BYOL.
. Para obtener información sobre compatibilidad con regiones de AWS, consulte https://cloud.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^].




== Cloud Volumes ONTAP para Azure

En Azure, puede poner en marcha Cloud Volumes ONTAP como un sistema de nodos únicos.

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de máquinas virtuales | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Almacenamiento subyacente 4+| Discos duros estándar gestionados, discos SSD estándar gestionados y discos SSD Premium gestionados, hasta 32 TIB por disco 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TIB | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. Si se habilita la clasificación por niveles de datos, el límite de capacidad de un sistema permanece igual. El límite de capacidad incluye tanto discos como almacenamiento de objetos.
. La organización en niveles de datos no se admite con el tipo de máquina virtual DS3_v2.
. Se habilita el rendimiento de escritura mejorado cuando se utilizan discos de almacenamiento Premium de Azure, pero no cuando se utiliza el tipo de máquina virtual DS3_v2.
. Para obtener información sobre la compatibilidad con Azure region, consulte https://cloud.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^].

